# Generated by Django 4.2.22 on 2025-08-17 15:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shelfmark', models.CharField(blank=True, max_length=500, null=True)),
                ('census_id', models.CharField(blank=True, db_index=True, max_length=40, null=True, verbose_name='ID#')),
                ('verification', models.CharField(choices=[('V', 'Verified'), ('U', 'Unverified'), ('F', 'False')], db_index=True, default='U', max_length=1)),
                ('fragment', models.BooleanField(db_index=True, default=False)),
                ('from_estc', models.BooleanField(default=False, verbose_name='From ESTC')),
                ('digital_facsimile_url', models.URLField(blank=True, max_length=500, null=True, verbose_name='Digital Facsimile URL')),
                ('binding', models.TextField(blank=True, null=True)),
                ('in_early_sammelband', models.BooleanField(default=False)),
                ('sammelband_notes', models.TextField(blank=True, null=True)),
                ('marginalia', models.TextField(blank=True, null=True)),
                ('local_notes', models.TextField(blank=True, null=True)),
                ('provenance_notes', models.TextField(blank=True, null=True)),
                ('height', models.FloatField(blank=True, null=True, verbose_name='Height (cm)')),
                ('width', models.FloatField(blank=True, null=True, verbose_name='Width (cm)')),
                ('bibliography', models.TextField(blank=True, null=True)),
                ('nonpublic_notes', models.TextField(blank=True, null=True)),
                ('created_by', models.CharField(blank=True, max_length=500, null=True)),
                ('verified_by', models.CharField(blank=True, max_length=500, null=True)),
                ('examined_by', models.CharField(blank=True, max_length=500, null=True)),
            ],
            options={
                'verbose_name_plural': 'Copies',
            },
        ),
        migrations.CreateModel(
            name='Edition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('edition_number', models.IntegerField()),
                ('edition_format', models.CharField(blank=True, max_length=10, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('city', models.CharField(blank=True, max_length=128, null=True)),
                ('state', models.CharField(blank=True, max_length=128, null=True, verbose_name='State/Province/County')),
                ('country', models.CharField(blank=True, max_length=128, null=True)),
                ('continent', models.CharField(blank=True, max_length=128, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('bio', models.CharField(blank=True, max_length=1024, null=True)),
                ('viaf', models.CharField(blank=True, max_length=256, null=True, verbose_name='VIAF')),
                ('start_century', models.CharField(blank=True, choices=[('17', 'Pre-1700'), ('18', '18th-Century'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('end_century', models.CharField(blank=True, choices=[('17', 'Pre-1700'), ('18', '18th-Century'), ('19', '19th-Century'), ('20', 'Post-1900')], max_length=2, null=True)),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('U', 'Unknown'), ('X', 'N/A')], max_length=1, null=True)),
            ],
            options={
                'verbose_name': 'Provenance Name',
                'verbose_name_plural': 'Provenance Names',
            },
        ),
        migrations.CreateModel(
            name='StaticPageText',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True, null=True)),
                ('viewname', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Static Page',
                'verbose_name_plural': 'Static Pages',
            },
        ),
        migrations.CreateModel(
            name='Title',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=128, unique=True)),
                ('apocryphal', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='titleicon/')),
            ],
        ),
        migrations.CreateModel(
            name='ProvenanceOwnership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('copy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='censusapp.copy')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ownerships', to='censusapp.provenancename')),
            ],
            options={
                'verbose_name': 'Provenance Record',
                'verbose_name_plural': 'Provenance Records',
            },
        ),
        migrations.CreateModel(
            name='Issue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stc_wing', models.CharField(blank=True, default='[Unknown]', max_length=20, null=True, verbose_name='STC / Wing')),
                ('estc', models.CharField(db_index=True, max_length=20, verbose_name='ESTC')),
                ('year', models.CharField(blank=True, max_length=20, null=True)),
                ('start_date', models.IntegerField(blank=True, default=0)),
                ('end_date', models.IntegerField(blank=True, default=0)),
                ('deep', models.CharField(blank=True, max_length=20, null=True, verbose_name='DEEP')),
                ('notes', models.TextField(blank=True, null=True)),
                ('edition', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='issues', to='censusapp.edition')),
            ],
        ),
        migrations.AddField(
            model_name='edition',
            name='title',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='editions', to='censusapp.title'),
        ),
        migrations.AddField(
            model_name='copy',
            name='issue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='copies', to='censusapp.issue'),
        ),
        migrations.AddField(
            model_name='copy',
            name='location',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='censusapp.location'),
        ),
        migrations.AddField(
            model_name='copy',
            name='provenance_names',
            field=models.ManyToManyField(through='censusapp.ProvenanceOwnership', to='censusapp.provenancename'),
        ),
    ]
