# Generated by Django 4.2.22 on 2025-08-20 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('censusapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='issue',
            options={'ordering': ['edition__edition_number', 'unknown_issue', 'issue_number']},
        ),
        migrations.AddField(
            model_name='issue',
            name='issue_number',
            field=models.PositiveIntegerField(blank=True, db_index=True, null=True),
        ),
        migrations.AddField(
            model_name='issue',
            name='unknown_issue',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='edition',
            name='edition_number',
            field=models.PositiveIntegerField(db_index=True),
        ),
        migrations.AlterField(
            model_name='issue',
            name='estc',
            field=models.CharField(blank=True, max_length=20, verbose_name='ESTC'),
        ),
        migrations.AlterField(
            model_name='issue',
            name='stc_wing',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='STC / Wing'),
        ),
        migrations.AddConstraint(
            model_name='issue',
            constraint=models.UniqueConstraint(fields=('edition', 'issue_number'), name='uniq_issue_number_per_edition'),
        ),
    ]
